apiVersion: v1
kind: Pod
metadata:
  name: memory-hog-api
spec:
  containers:
  - name: stress-test
    image: polinux/stress
    # This command will use 50MiB of memory (50 * 1MB allocations)
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "10Mi"
      limits:
        memory: "100Mi"
        