apiVersion: v1
kind: Pod
metadata:
  name: backend-api
  labels:
    app: backend-v1  # Pay attention to this label
spec:
  containers:
  - name: main
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-api # This is the intentional error
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    