# 1. THE ENTRANCE (Service)
apiVersion: v1
kind: Service
metadata:
  name: web-entry
  labels:
    app: web-worker
spec:
  type: NodePort
  selector:
    app: web-worker
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 30007
  - name: metrics          
    port: 9113
    targetPort: 9113
---
# 2. THE CONFIG (Enables Nginx Status Page)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  status.conf: |
    server {
        listen 8080;
        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
---
# 3. THE BRAINS (Deployment with Sidecar)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-worker-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-worker
  template:
    metadata:
      labels:
        app: web-worker
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        - containerPort: 8080  # <--- Added so exporter can reach status page
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/status.conf
          subPath: status.conf
      - name: metrics-exporter
        image: nginx/nginx-prometheus-exporter:1.1.0
        args:
        - -nginx.scrape-uri=http://127.0.0.1:8080/nginx_status
        ports:
        - name: metrics
          containerPort: 9113
      volumes:
      - name: config
        configMap:
          name: nginx-config
---
# 4. THE EYES (ServiceMonitor)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-worker-monitor
  labels:
    release: my-monitor    # <--- MUST match your Helm release name
spec:
  selector:
    matchLabels:
      app: web-worker
  endpoints:
  - port: metrics          # <--- Targets the exporter, not the web traffic
    interval: 10s